/* ============================================================
   crm-invoice.js — Invoice + Receipt Generation & Creation Modal
   Provides: openCreateInvoiceModal, openInvoicePreviewModal,
             createInvoiceAndReceipt (CRM form approval flow)
   ============================================================ */
(function () {

/* ── MODULE STATE ─────────────────────────────────────────── */
let _ctx      = {};     // { studentId, familyId, leadId, convId, branch }
let _invType  = 'new';  // 'new' | 'renewal'
let _nameAuto = true;
let _pkgHours = 24;
let _selCrsId = '';

/* ── HELPERS ──────────────────────────────────────────────── */
function getMasterAdmin(branch) {
  return (DB.staff||[]).find(s =>
    s.adminTier === 'master' &&
    (s.branches||[]).includes(branch)
  ) || (DB.staff||[]).find(s => s.adminTier === 'master');
}

function _sigBlock(branch) {
  const ma = getMasterAdmin(branch);
  return `<div style="display:flex;justify-content:flex-end;margin-top:20px;
                      padding-top:14px;border-top:1px solid #f3f4f6">
    <div style="text-align:center;min-width:160px">
      ${ma?.signature
        ? `<img src="${ma.signature}" style="max-height:48px;max-width:160px;object-fit:contain;
                                             display:block;margin:0 auto 6px">`
        : `<div style="height:48px;border-bottom:1.5px solid #374151;margin-bottom:6px"></div>`}
      <div style="font-size:10px;color:#374151;font-weight:600">${ma?.name || '—'}</div>
      <div style="font-size:9px;color:#9ca3af">Authorized Signatory · ${branch} Branch</div>
    </div>
  </div>`;
}

function _esc(s) {
  return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}
/* Price matrix: Course(Subject+Grade) × Package × Branch — fallback pkgPrice */
function _price(hours, branch, courseId, subject, grade) {
  return Utils.coursePrice({ courseId, subject, grade, hours, branch });
}
function _autoName(subj, grade, hours) {
  return `${subj} ${grade} · ${hours}h.`;
}
function _nextInvId() {
  return 'INV-2026-' + String(Date.now()).slice(-4);
}
function _refNo(id) {
  const n = parseInt((id||'').split('-').pop()||'0', 10);
  return `6905-${String(n).padStart(2,'0')}`;
}

/* ── RECEIPT SVG ──────────────────────────────────────────── */
function _receiptSvg(rec) {
  const x  = (lbl, y, val, fw) => `<text x="20" y="${y}" fill="#6b7280" font-size="10">${lbl}</text><text x="190" y="${y}" fill="#374151" font-size="11"${fw?' font-weight="600"':''}>${val}</text>`;
  const hr = y => `<line x1="20" y1="${y}" x2="380" y2="${y}" stroke="#f3f4f6" stroke-width="1"/>`;
  const inv = _esc(rec.invoiceId||(rec.id||'').replace('RCP','INV'));
  const amt = Number(rec.amount||0).toLocaleString('en-US');
  return `<svg xmlns="http://www.w3.org/2000/svg" width="400" height="500" font-family="Arial,sans-serif">
<rect width="400" height="500" fill="#fff" rx="4" stroke="#e5e7eb" stroke-width="1.5"/>
<rect width="400" height="68" fill="#4f46e5" rx="4"/><rect y="54" width="400" height="14" fill="#4f46e5"/>
<text x="20" y="28" fill="#fff" font-size="16" font-weight="bold">NockAcademy</text>
<text x="20" y="48" fill="#a5b4fc" font-size="10">Tutoring Center</text>
<text x="380" y="30" fill="#fff" font-size="17" font-weight="bold" text-anchor="end">RECEIPT</text>
<text x="380" y="50" fill="#a5b4fc" font-size="9" text-anchor="end">${_esc(rec.id||'')}</text>
${x('Invoice Ref.',100,inv,true)}${x('Date',120,_esc(rec.paidAt||rec.date||''),true)}
${hr(134)}${x('Student',154,_esc(rec.student||''),true)}${x('Branch',172,_esc(rec.branch||''),false)}
${hr(186)}${x('Course',206,_esc(rec.course||''),true)}${x('Payment Method',224,_esc(rec.method||'Bank Transfer'),false)}
${x('Reference No.',242,_esc(rec.refNo||''),false)}
<line x1="20" y1="258" x2="380" y2="258" stroke="#e5e7eb" stroke-width="1.5"/>
<text x="20" y="280" fill="#6b7280" font-size="11">Total Amount (THB)</text>
<text x="380" y="296" fill="#059669" font-size="30" font-weight="800" text-anchor="end">${amt}</text>
<line x1="20" y1="314" x2="380" y2="314" stroke="#e5e7eb" stroke-width="1.5"/>
<rect x="20" y="330" width="110" height="46" rx="6" fill="#dcfce7" stroke="#16a34a" stroke-width="2"/>
<text x="75" y="350" text-anchor="middle" fill="#15803d" font-size="13" font-weight="800">PAID</text>
<text x="75" y="367" text-anchor="middle" fill="#15803d" font-size="8">${_esc(rec.paidAt||'')}</text>
<text x="145" y="347" fill="#6b7280" font-size="10">Approved by</text>
<text x="145" y="364" fill="#374151" font-size="11" font-weight="600">${_esc(rec.stampedBy||'Admin')}</text>
${hr(394)}
<text x="200" y="414" text-anchor="middle" fill="#9ca3af" font-size="9">Thank you for choosing NockAcademy</text>
<text x="200" y="430" text-anchor="middle" fill="#d1d5db" font-size="8">Official receipt generated by NockERP</text>
</svg>`;
}
function _receiptDataUrl(rec) {
  try { return 'data:image/svg+xml;base64,' + btoa(unescape(encodeURIComponent(_receiptSvg(rec)))); }
  catch(e) { return ''; }
}

/* ── INVOICE CREATION MODAL ───────────────────────────────── */
window.openCreateInvoiceModal = function(ctx = {}) {
  _ctx      = ctx;
  _invType  = 'new';
  _nameAuto = true;
  _pkgHours = 24;
  _selCrsId = '';

  const student = ctx.studentId ? DB.students.find(s => s.id === ctx.studentId) : null;
  const family  = ctx.familyId  ? DB.families.find(f => f.id === ctx.familyId)  : null;
  const lead    = ctx.leadId    ? DB.leads.find(l => l.id === ctx.leadId)        : null;
  _ctx.branch   = student?.branch || family?.branch || lead?.branch || 'Sukhumvit';

  // Person display
  let personHTML;
  if (student) {
    personHTML = `<div style="background:var(--md-surface-low);border-radius:8px;padding:10px 12px;
        display:flex;gap:10px;align-items:center">
      ${UI.avatar(student.name[0], 'sm')}
      <div>
        <div style="font-size:13px;font-weight:600;color:var(--md-on-surface)">${student.name}</div>
        <div class="text-muted" style="font-size:11px">${student.grade} · ${student.branch}</div>
      </div>
    </div>`;
  } else if (family) {
    personHTML = `<div style="background:var(--md-surface-low);border-radius:8px;padding:10px 12px">
      <div style="font-size:13px;font-weight:600">${family.name}</div>
      <div class="text-muted" style="font-size:11px">${family.branch}</div>
    </div>`;
  } else {
    personHTML = `<div>
      <div class="form-label">Student</div>
      <select class="form-input" id="inv-person-sel" onchange="invPersonChanged(this.value)" style="margin-top:6px">
        <option value="">— Select Student —</option>
        ${DB.students.map(s => `<option value="${s.id}">${s.name} · ${s.grade}</option>`).join('')}
      </select>
    </div>`;
  }

  const courseOpts = DB.courses.map(c => {
    const tag = c.type === 'bundle' ? ' [Bundle]' : '';
    return `<option value="${c.id}">${c.name}${tag}</option>`;
  }).join('');

  const hasRenewal = (student?.courses?.length || 0) > 0;
  const renewOpts  = (student?.courses || []).map((c, i) =>
    `<option value="${i}">${c.name}</option>`
  ).join('');

  const subjOpts  = Utils.subjectsFor().map(s => `<option value="${s}">${s}</option>`).join('');
  const gradeOpts = CONST.GRADES.map(g => `<option value="${g}">${g}</option>`).join('');

  const bodyHTML = `<div style="display:flex;flex-direction:column;gap:14px">
    ${personHTML}

    <div>
      <div class="form-label">Type</div>
      <div style="display:flex;gap:6px;margin-top:6px">
        <button class="btn btn-primary btn-sm" id="inv-btn-new" onclick="invSetType('new')">
          ${UI.icon('add_circle','sm')} New Enrollment
        </button>
        ${hasRenewal ? `<button class="btn btn-secondary btn-sm" id="inv-btn-renewal" onclick="invSetType('renewal')">
          ${UI.icon('autorenew','sm')} Renewal
        </button>` : ''}
      </div>
    </div>

    <div id="inv-sec-new">
      <div class="form-label">Course</div>
      <select class="form-input" id="inv-course-sel" onchange="invOnCourseChange(this.value)" style="margin-top:6px">
        <option value="">— Select existing course —</option>
        ${courseOpts}
        <option value="__custom__">+ Custom</option>
      </select>
      <!-- Bundle course block picker (shown only for Bundle courses) -->
      <div id="inv-bundle" style="display:none;margin-top:12px;padding:12px;border-radius:8px;
           background:var(--md-surface-mid);border:1.5px solid var(--md-outline-variant)">
        <div style="font-size:11px;font-weight:700;margin-bottom:10px;color:var(--md-on-surface)">
          ${UI.icon('layers','sm')} Bundle Billing
        </div>
        <div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:10px">
          <div>
            <div class="form-label">Blocks to Pay</div>
            <div style="display:flex;gap:6px;margin-top:6px">
              ${[1,2,3].map(n=>`<button class="btn btn-sm ${n===1?'btn-primary':'btn-secondary'}"
                data-blk="${n}" onclick="invSetBlocks(${n})">${n} Block${n>1?'s':''}</button>`).join('')}
            </div>
          </div>
          <div>
            <div class="form-label">Admission Fee</div>
            <label style="display:flex;align-items:center;gap:8px;cursor:pointer;font-size:12px;margin-top:10px">
              <input type="checkbox" id="inv-admission" onchange="invBundleRecalcFromUI()"
                style="width:16px;height:16px">
              ฿1,500 (first time)
            </label>
          </div>
        </div>
      </div>

      <div id="inv-custom" style="display:none;flex-direction:column;gap:10px;margin-top:12px">
        <div style="display:grid;grid-template-columns:1fr 1fr;gap:8px">
          <div><div class="form-label">Subject</div>
            <select class="form-input" id="inv-subj" onchange="invRecalc()">${subjOpts}</select></div>
          <div><div class="form-label">Grade</div>
            <select class="form-input" id="inv-grade" onchange="invRecalc()">${gradeOpts}</select></div>
        </div>
        <div>
          <div class="form-label">Package</div>
          <div style="display:flex;gap:6px;margin-top:6px">
            ${[24,48,72,96].map(h => `<button class="btn btn-sm ${h===24?'btn-primary':'btn-secondary'}" data-pkg="${h}" onclick="invSetPkg(${h})">${h}h</button>`).join('')}
          </div>
        </div>
        <div>
          <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:6px">
            <div class="form-label" style="margin-bottom:0">Course Name</div>
            <div style="display:flex;gap:4px">
              <button class="btn btn-sm btn-primary"   id="inv-nm-auto"   onclick="invSetNameMode(true)">Auto</button>
              <button class="btn btn-sm btn-secondary" id="inv-nm-custom" onclick="invSetNameMode(false)">Custom</button>
            </div>
          </div>
          <input class="form-input" id="inv-cname" placeholder="Math ป.5 · 24h." readonly>
          <label style="display:flex;align-items:center;gap:8px;cursor:pointer;font-size:12px;margin-top:8px">
            <input type="checkbox" id="inv-save-crs" checked>
            Save as Branch Course
          </label>
        </div>
      </div>
    </div>

    <div id="inv-sec-renewal" style="display:none">
      <div class="form-label">Enrollment to Renew</div>
      <select class="form-input" id="inv-renewal-sel" onchange="invOnRenewalChange(this.value)" style="margin-top:6px">
        <option value="">— Select enrollment —</option>
        ${renewOpts}
      </select>
    </div>

    <div id="inv-summary" style="display:none;background:var(--md-primary-container);border-radius:8px;padding:12px">
      <div style="display:flex;justify-content:space-between;align-items:center">
        <div>
          <div id="inv-sum-name"  style="font-size:13px;font-weight:600;color:var(--md-on-primary-container)"></div>
          <div id="inv-sum-hours" style="font-size:11px;color:var(--md-primary);margin-top:2px"></div>
        </div>
        <div id="inv-sum-price"  style="font-size:20px;font-weight:800;color:var(--md-primary)"></div>
      </div>
    </div>
  </div>`;

  const footer = `
    <button class="btn btn-secondary" onclick="Modal.close('modal-invoice-create')">Cancel</button>
    <button class="btn btn-primary" id="inv-submit" disabled onclick="invSubmit()">
      ${UI.icon('receipt_long','sm')} Create Invoice
    </button>`;

  Modal.create('modal-invoice-create', `${UI.icon('receipt_long')} Create Invoice`, bodyHTML, footer);
};

/* ── Modal handlers (global for onclick) ─────────────────── */
window.invPersonChanged = function(sid) {
  _ctx.studentId = sid;
  const s = DB.students.find(st => st.id === sid);
  _ctx.branch = s?.branch || 'Sukhumvit';
};

window.invSetType = function(type) {
  _invType = type;
  const isNew = type === 'new';
  document.getElementById('inv-sec-new').style.display     = isNew ? '' : 'none';
  document.getElementById('inv-sec-renewal').style.display = isNew ? 'none' : '';
  document.getElementById('inv-summary').style.display     = 'none';
  document.getElementById('inv-submit').disabled           = true;
  document.getElementById('inv-btn-new').className = `btn btn-sm ${isNew?'btn-primary':'btn-secondary'}`;
  const rb = document.getElementById('inv-btn-renewal');
  if (rb) rb.className = `btn btn-sm ${!isNew?'btn-primary':'btn-secondary'}`;
};

window.invOnCourseChange = function(val) {
  _selCrsId = val;
  const custom = document.getElementById('inv-custom');
  const bundleSec = document.getElementById('inv-bundle');
  if (val === '__custom__') {
    if (custom)    custom.style.display = 'flex';
    if (bundleSec) bundleSec.style.display = 'none';
    invRecalc();
  } else {
    if (custom) custom.style.display = 'none';
    if (val) {
      const c = DB.courses.find(x => x.id === val);
      if (c && (c.courseType === 'bundle' || c.type === 'bundle')) {
        // Bundle course: show block picker
        if (bundleSec) bundleSec.style.display = '';
        invBundleRecalc(c);
      } else {
        if (bundleSec) bundleSec.style.display = 'none';
        if (c) {
          const h = c.subjects[0]?.hours || 24;
          invShowSummary(c.name, h, _price(h, _ctx.branch, c.id));
        }
      }
    } else {
      if (bundleSec) bundleSec.style.display = 'none';
      document.getElementById('inv-summary').style.display = 'none';
      document.getElementById('inv-submit').disabled = true;
    }
  }
};

window.invSetPkg = function(h) {
  _pkgHours = h;
  document.querySelectorAll('[data-pkg]').forEach(b => {
    b.className = `btn btn-sm ${Number(b.dataset.pkg) === h ? 'btn-primary' : 'btn-secondary'}`;
  });
  invRecalc();
};

window.invRecalc = function() {
  const subj  = document.getElementById('inv-subj')?.value  || 'Math';
  const grade = document.getElementById('inv-grade')?.value || 'ป.5';
  const price = _price(_pkgHours, _ctx.branch, null, subj, grade);
  if (_nameAuto) {
    const el = document.getElementById('inv-cname');
    if (el) el.value = _autoName(subj, grade, _pkgHours);
  }
  invShowSummary(document.getElementById('inv-cname')?.value || `${subj} ${grade}`, _pkgHours, price);
};

let _bundleBlocks = 1;
let _bundleCourse = null;

window.invSetBlocks = function(n) {
  _bundleBlocks = n;
  document.querySelectorAll('[data-blk]').forEach(b => {
    b.className = `btn btn-sm ${Number(b.dataset.blk) === n ? 'btn-primary' : 'btn-secondary'}`;
  });
  if (_bundleCourse) invBundleRecalc(_bundleCourse);
};

window.invBundleRecalcFromUI = function() {
  if (_bundleCourse) invBundleRecalc(_bundleCourse);
};

function invBundleRecalc(c) {
  _bundleCourse = c;
  const admissionChk = document.getElementById('inv-admission');
  const admissionFee = admissionChk?.checked ? (c.admissionFee || 1500) : 0;
  const blockPrice   = c.billingBlockPrice || 5900;
  const total        = _bundleBlocks * blockPrice + admissionFee;
  const hrs          = (c.billingBlockSize || 4) * 2 * _bundleBlocks; // 2h/slot × 4 classes × blocks
  const label        = `${c.name} · ${_bundleBlocks} block${_bundleBlocks>1?'s':''}${admissionFee?` + ฿${admissionFee.toLocaleString()} admission`:''}`;
  invShowSummary(label, hrs, total);
}

window.invSetNameMode = function(auto) {
  _nameAuto = auto;
  const el = document.getElementById('inv-cname');
  if (el) el.readOnly = auto;
  document.getElementById('inv-nm-auto').className   = `btn btn-sm ${auto?'btn-primary':'btn-secondary'}`;
  document.getElementById('inv-nm-custom').className = `btn btn-sm ${!auto?'btn-primary':'btn-secondary'}`;
  if (auto) invRecalc();
};

window.invOnRenewalChange = function(idx) {
  const student = DB.students.find(s => s.id === _ctx.studentId);
  const c = student?.courses?.[Number(idx)];
  if (!c) return;
  invShowSummary(c.name, c.hours, _price(c.hours, _ctx.branch, c.courseId));
};

function invShowSummary(name, hours, price) {
  document.getElementById('inv-summary').style.display = '';
  const nm = document.getElementById('inv-sum-name');
  const hr = document.getElementById('inv-sum-hours');
  const pr = document.getElementById('inv-sum-price');
  if (nm) nm.textContent = name;
  if (hr) hr.textContent = `${hours}h · ${_ctx.branch}`;
  if (pr) pr.textContent = price ? `฿${price.toLocaleString()}` : '—';
  const btn = document.getElementById('inv-submit');
  if (btn) btn.disabled = !price;
}

window.invSubmit = function() {
  const student = _ctx.studentId ? DB.students.find(s => s.id === _ctx.studentId) : null;
  const family  = _ctx.familyId  ? DB.families.find(f => f.id === _ctx.familyId)
                : student ? DB.families.find(f => f.name === student.family) : null;

  let courseName, hours, price, courseId = null;

  if (_invType === 'renewal') {
    const sel = document.getElementById('inv-renewal-sel');
    const c   = student?.courses?.[Number(sel?.value || 0)];
    if (!c) return;
    courseName = c.name; hours = c.hours; price = _price(hours, _ctx.branch, c.courseId);
  } else if (_selCrsId && _selCrsId !== '__custom__') {
    const c = DB.courses.find(x => x.id === _selCrsId);
    if (!c) return;
    courseId = c.id;
    if (c.courseType === 'bundle' || c.type === 'bundle') {
      const admissionFee = document.getElementById('inv-admission')?.checked ? (c.admissionFee||1500) : 0;
      const blockPrice   = c.billingBlockPrice || 5900;
      hours = (c.billingBlockSize||4) * 2 * _bundleBlocks;
      price = _bundleBlocks * blockPrice + admissionFee;
      courseName = `${c.name} · ${_bundleBlocks} block${_bundleBlocks>1?'s':''}`;
    } else {
      courseName = c.name; hours = c.subjects[0]?.hours || 24;
      price = _price(hours, _ctx.branch, c.id);
    }
  } else {
    const subj  = document.getElementById('inv-subj')?.value  || 'Math';
    const grade = document.getElementById('inv-grade')?.value || 'ป.5';
    courseName  = document.getElementById('inv-cname')?.value || _autoName(subj, grade, _pkgHours);
    hours = _pkgHours;
    price = _price(hours, _ctx.branch, null, subj, grade);
    if (document.getElementById('inv-save-crs')?.checked) {
      const nc = { id:'crs-'+String(Date.now()).slice(-4), name:courseName, type:'single',
        subjects:[{subject:subj, grade, hours}], branches:[_ctx.branch], promotions:[], createdAt:'2026-05-27' };
      DB.courses.push(nc);
      courseId = nc.id;
    }
  }

  const invId   = _nextInvId();
  const invoice = {
    id:invId, studentId:student?.id||null, familyId:family?.id||null, courseId,
    course:`${courseName}`, hours, amount:price,
    date:'27 May 2026', status:'draft',
    createdFrom: _ctx.convId ? 'inbox' : 'manual', branch:_ctx.branch,
  };
  DB.invoices.push(invoice);

  if (_ctx.convId) {
    const msgs = DB.messages[_ctx.convId] = DB.messages[_ctx.convId] || [];
    msgs.push({ type:'invoice_card', invId, courseName, hours, amount:price, time:'Now', sender:'Admin Nock' });
    const conv = DB.conversations.find(c => c.id === _ctx.convId);
    if (conv) { conv.time = 'Now'; conv.preview = `Invoice ${invId} created`; }
  }

  Modal.close('modal-invoice-create');
  showToast(`${invId} created ✓`, 'success');
  window._refreshInboxList?.();
  window._refreshBilling?.();
};

/* ── INVOICE PREVIEW MODAL ────────────────────────────────── */
window.openInvoicePreviewModal = function(invId) {
  const inv = DB.invoices.find(i => i.id === invId);
  if (!inv) { showToast('Invoice not found', 'error'); return; }

  const student = inv.studentId ? DB.students.find(s => s.id === inv.studentId) : null;
  const family  = inv.familyId  ? DB.families.find(f => f.id === inv.familyId)  : null;
  const refNo   = _refNo(inv.id);

  const SM = { paid:{cls:'green',label:'Paid'}, pending:{cls:'yellow',label:'Pending Verification'},
               draft:{cls:'gray',label:'Draft'}, sent:{cls:'blue',label:'Sent'} };
  const sm = SM[inv.status] || SM.draft;

  const bodyHTML = `<div style="font-family:Arial,sans-serif;max-width:540px;margin:0 auto;
      padding:24px;border:1px solid var(--md-outline-variant);border-radius:8px;background:#fff">
    <div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:20px">
      <div>
        <div style="font-size:16px;font-weight:700;color:#1a1d23">Nock Academy</div>
        <div style="font-size:10px;color:#9ca3af;margin-top:2px">${inv.branch} Branch</div>
        <div style="font-size:10px;color:#9ca3af">Tax ID: 0-1053-56789-01-2</div>
      </div>
      <div style="text-align:right">
        <div style="font-size:20px;font-weight:800;color:var(--md-primary)">INVOICE</div>
        <div style="font-size:10px;color:#6b7280">ใบแจ้งหนี้</div>
      </div>
    </div>
    <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:8px;background:#f9fafb;
        padding:10px 14px;border-radius:6px;margin-bottom:16px">
      <div><div style="font-size:9px;color:#9ca3af;text-transform:uppercase">NO.</div>
        <div style="font-weight:700;font-size:13px;color:var(--md-primary)">${refNo}</div></div>
      <div><div style="font-size:9px;color:#9ca3af;text-transform:uppercase">Date</div>
        <div style="font-weight:600;font-size:12px">${inv.date}</div></div>
      <div><div style="font-size:9px;color:#9ca3af;text-transform:uppercase">Status</div>
        <div>${UI.badge(sm.label, sm.cls)}</div></div>
    </div>
    <div style="margin-bottom:16px">
      <div style="font-size:9px;color:#9ca3af;text-transform:uppercase;margin-bottom:4px">Bill To</div>
      <div style="font-weight:600;font-size:13px">${student?.name || '—'}</div>
      <div style="font-size:11px;color:#6b7280">${family?.name || ''}</div>
    </div>
    <table style="width:100%;border-collapse:collapse;margin-bottom:16px">
      <thead><tr style="background:#f3f4f6">
        <th style="padding:8px;font-size:10px;color:#6b7280;font-weight:600;text-align:left">#</th>
        <th style="padding:8px;font-size:10px;color:#6b7280;font-weight:600;text-align:left">Description</th>
        <th style="padding:8px;font-size:10px;color:#6b7280;font-weight:600;text-align:right">Amount</th>
      </tr></thead>
      <tbody><tr>
        <td style="padding:10px 8px;border-bottom:1px solid #f3f4f6">1</td>
        <td style="padding:10px 8px;border-bottom:1px solid #f3f4f6;font-weight:500">${inv.course}</td>
        <td style="padding:10px 8px;border-bottom:1px solid #f3f4f6;text-align:right;font-weight:700">฿${inv.amount.toLocaleString()}</td>
      </tr></tbody>
    </table>
    <div style="display:flex;justify-content:space-between;gap:16px;margin-bottom:16px">
      <div style="flex:1;background:#f0fdf4;border:1px solid #bbf7d0;border-radius:6px;padding:10px;font-size:11px">
        <div style="font-weight:600;margin-bottom:4px;color:#374151">ช่องทางชำระเงิน</div>
        <div>ธนาคารกรุงศรีอยุธยา</div>
        <div>เลขที่บัญชี: 5991616726</div>
        <div>ชื่อบัญชี: Nock Academy Co., Ltd.</div>
      </div>
      <div style="min-width:160px">
        <table style="width:100%;font-size:11px">
          <tr><td style="padding:4px 8px;color:#6b7280">Sub Total</td>
            <td style="padding:4px 8px;text-align:right">฿${inv.amount.toLocaleString()}</td></tr>
          <tr><td style="padding:4px 8px;color:#6b7280">VAT 7%</td>
            <td style="padding:4px 8px;text-align:right">฿0</td></tr>
          <tr style="border-top:2px solid #1a1d23">
            <td style="padding:6px 8px;font-weight:700">Total</td>
            <td style="padding:6px 8px;text-align:right;font-weight:700;font-size:14px;color:var(--md-primary)">
              ฿${inv.amount.toLocaleString()}</td>
          </tr>
        </table>
      </div>
    </div>
    ${_sigBlock(inv.branch || 'Sukhumvit')}
  </div>`;

  const footer = `
    <button class="btn btn-secondary" onclick="copyInvoiceLink('${invId}')">
      ${UI.icon('link','sm')} Copy Link
    </button>
    <button class="btn btn-secondary" onclick="Modal.close('modal-invoice-preview')">Close</button>`;

  Modal.create('modal-invoice-preview', `${UI.icon('receipt_long')} ${invId}`, bodyHTML, footer, 'modal-lg');
};

window.copyInvoiceLink = function(invId) {
  const link = `${location.href.split('#')[0]}#invoice=${invId}`;
  navigator.clipboard?.writeText(link).then(() => showToast('Link copied ✓', 'success'))
    .catch(() => showToast('Copy failed — use browser address bar', 'error'));
};

/* ── CRM FORM APPROVAL: createInvoiceAndReceipt ───────────── */
function findConv(lead) { return window._crmFindConv?.(lead) || null; }

window.createInvoiceAndReceipt = function(subId) {
  const sub  = (DB.formSubmissions || []).find(s => s.id === subId);
  if (!sub) return;
  const lead = DB.leads.find(l => l.id === sub.leadId);
  if (!lead) return;
  const d = sub.data || {};

  if (d.payment?.slipAttached && !d.payment?.slipDataUrl) {
    d.payment.slipDataUrl = window._crmMockSlip?.(d.course?.price || 7200) || '';
    d.payment.slipName    = d.payment.slipName || 'payment_slip.jpg';
  }

  const suffix     = String(Date.now()).slice(-4);
  const invId      = 'INV-2026-' + suffix;
  const rcpId      = 'RCP-2026-' + suffix;
  const refNo      = 'NCK' + String(Date.now()).slice(-8);
  const dateStr    = '27 May 2026';
  const branch     = lead.branch || d.schedule?.branch || 'Sukhumvit';
  const familyName = d.family?.parent1Name
    ? d.family.parent1Name.replace(/\s+(Dad|Mom|Parent|คุณพ่อ|คุณแม่)$/i,'').trim() + ' Family'
    : lead.name.split(' ').slice(-1)[0] + ' Family';
  const coursePkg  = `${d.course?.name || lead.course} · ${d.course?.hours || 24}h.`;

  const invoice = {
    id:invId, date:dateStr, student:lead.name, family:familyName, branch,
    course:d.course?.name || lead.course, hours:d.course?.hours || 24,
    amount:d.course?.price || 7200, method:d.payment?.method || 'Bank Transfer',
    status:'paid',
    payslip:{dataUrl:d.payment?.slipDataUrl||'', name:d.payment?.slipName||'payment_slip.jpg', refNo, paidAt:dateStr},
  };
  const receipt = {
    id:rcpId, invoiceId:invId, student:invoice.student, family:invoice.family,
    branch:invoice.branch, course:coursePkg, amount:invoice.amount,
    method:invoice.method, paidAt:dateStr, refNo, stampedBy:'Admin Nock',
  };
  receipt.dataUrl = _receiptDataUrl(receipt);

  sub.status = 'approved'; sub.invoiceId = invId; sub.receiptId = rcpId;
  lead.formPending = false; lead.stage = 'enrolled';

  // Push to central pools
  DB.invoices.push({ id:invId, studentId:null, familyId:null, courseId:null,
    course:coursePkg, hours:invoice.hours, amount:invoice.amount,
    date:dateStr, status:'paid', createdFrom:'crm', branch });
  DB.receipts.push({ id:rcpId, invoiceId:invId, studentId:null, familyId:null,
    amount:receipt.amount, paidAt:dateStr, stampedBy:'Admin Nock', branch, method:invoice.method, refNo });

  if (!DB.customers.find(c => c.name === lead.name)) {
    DB.customers.push({
      name:lead.name, family:familyName, branch,
      course:invoice.course, pkg:coursePkg,
      teacher:d.schedule?.teacher||'TBD',
      schedule:(d.schedule?.label||'TBD').replace(/Every\s+/i,'').replace(/\s+\d{4}/,'').replace(/, \d{2}:\d{2}.*/,''),
      remain:invoice.hours, total:invoice.hours,
      since:'May 2026', until:'Nov 2026', status:'active',
      phone:d.family?.parent1Phone||lead.phone||'',
      line:d.family?.parent1Line||lead.line||'',
      revenue:invoice.amount,
    });
  }

  const existStu = DB.students.find(s => s.name === lead.name);
  if (!existStu) {
    DB.students.push({
      id:'stu_'+lead.id, name:lead.name, age:lead.age||0, branch, family:familyName,
      line:d.family?.parent1Line||lead.line||'', phone:d.family?.parent1Phone||lead.phone||'',
      enrollDate:dateStr, teacher:d.schedule?.teacher||'TBD', status:'active',
      courses:[{name:invoice.course, hours:invoice.hours, used:0, left:invoice.hours, price:invoice.amount}],
      schedule:[], attendance:[],
      invoices:[{...invoice}], receipts:[{...receipt}],
      notes:[{type:'admin', text:`Enrolled via CRM · ${invoice.course} · ${invId}`, author:'Admin Nock', date:'27 May'}],
    });
  } else {
    (existStu.invoices = existStu.invoices||[]).push({...invoice});
    (existStu.receipts = existStu.receipts||[]).push({...receipt});
  }

  if (!DB.families.find(f => f.name === familyName)) {
    DB.families.push({
      id:'fam_'+lead.id, name:familyName, branch,
      assignee:'Admin Nock', status:'active',
      totalPaid:invoice.amount, invoiceCount:1,
      lastContact:'Today', channel:lead.line?'LINE':'Phone', unreadCount:0,
      parents:[{role:'Parent', name:d.family?.parent1Name||'',
        line:d.family?.parent1Line||lead.line||'',
        phone:d.family?.parent1Phone||lead.phone||'',
        email:'', lineActive:!!(d.family?.parent1Line||lead.line)}],
      students:[lead.name],
      notes:[{type:'admin', text:`Enrolled ${invoice.course} · from CRM`, author:'Admin Nock', date:'27 May'}],
    });
  }

  const conv = findConv(lead);
  if (conv) {
    conv.unread = true; conv.time = 'Now';
    conv.preview = `${invId} issued — receipt sent`;
    (DB.messages[conv.id] = DB.messages[conv.id]||[]).push(
      {type:'staff', text:`Enrollment confirmed! ${lead.name} is now enrolled in ${invoice.course}. Receipt attached.`, time:'Now', sender:'Admin Nock'},
      {type:'receipt', invId, rcpId, receiptDataUrl:receipt.dataUrl, amount:invoice.amount, coursePkg, time:'Now', sender:'System'}
    );
  }

  window._refreshPipeline?.();
  window._refreshInboxList?.();
  const ub = document.getElementById('badge-inbox');
  if (ub) ub.textContent = DB.conversations.filter(c=>c.unread).length || '';
  Modal.close('modal-form-review');
  showToast(`${invId} + ${rcpId} created & sent to ${lead.name} ✓`, 'success');
};

})();
