import React, { useState, useEffect } from 'react'
import { createRoot } from 'react-dom/client'
import { IconSchool, IconLayoutDashboard, IconUsers, IconMessage, IconCalendar, IconUser, IconUsersGroup, IconIdBadge, IconBook, IconChalkboard, IconClock, IconClipboardCheck, IconFileText, IconCreditCard, IconListCheck, IconChartBar, IconSettings, IconHistory, IconBell, IconSearch, IconSun, IconMoon, IconLayoutSidebar, IconChevronRight, IconChevronDown, IconSelector, IconPlus, IconArrowRight, IconArrowUpRight, IconRefresh, IconBuilding, IconLogout, IconDownload, IconCheck, IconPhone } from '@tabler/icons-react'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator } from '@/components/ui/dropdown-menu'
import './theme.css'
import Students from './Students'
import {installOperationsBridge} from './lib/operations-bridge'

const groups = [
 ['Workspace', [['dashboard','Overview',IconLayoutDashboard],['crm','CRM',IconUsers],['inbox','Inbox',IconMessage],['calendar','Calendar',IconCalendar]]],
 ['People', [['students','Students',IconSchool],['families','Families',IconUsersGroup],['staff','Staff',IconIdBadge]]],
 ['Learning', [['courses','Courses',IconBook],['classes','Classes',IconChalkboard],['sessions','Sessions',IconClock],['attendance','Attendance',IconClipboardCheck],['summaries','Summaries',IconFileText]]],
 ['Management', [['billing','Billing',IconCreditCard],['tasks','Tasks',IconListCheck],['reports','Reports',IconChartBar]]],
 ['System', [['settings','Settings',IconSettings],['logs','Activity log',IconHistory]]]
]
const entries=groups.flatMap(g=>g[1])
const db=window.DB
const modelDate=db.dayHeaders.find(d=>d.isToday)?.date || '2026-05-13'
const money=n=>'฿'+Number(n).toLocaleString('en-US')
const initials=name=>name.split(' ').map(n=>n[0]).slice(0,2).join('')
const emit=()=>window.dispatchEvent(new Event('erp:data'))
const originalShowView=window.__erpOriginalShowView ||= window.showView
window.showView=function(id){originalShowView(id); window.history.replaceState(null,'','#'+id);window.dispatchEvent(new CustomEvent('erp:navigate',{detail:id}));document.body.classList.remove('sidebar-open')}
const navigate=id=>window.showView(id)
function useRefresh(){const [n,setN]=useState(0);useEffect(()=>{const refresh=()=>setN(v=>v+1);window.addEventListener('erp:data',refresh);window.addEventListener('erp:navigate',refresh);return()=>{window.removeEventListener('erp:data',refresh);window.removeEventListener('erp:navigate',refresh)}},[]);return n}
function Avatar({name}){return <span className="avatar">{initials(name)}</span>}
function ActionButton({children,className="",...props}){return <Button className={"erp-button "+className} {...props}>{children}</Button>}

function Shell(){
 const [view,setView]=useState(location.hash.slice(1)||'dashboard')
 const [dark,setDark]=useState(()=>{try{return localStorage.getItem('nockerp-theme')==='dark'}catch{return false}})
 const [search,setSearch]=useState(false),[query,setQuery]=useState('')
 const [user,setUser]=useState({...window.CURRENT_USER})
 useEffect(()=>{document.documentElement.classList.toggle('dark',dark);try{localStorage.setItem('nockerp-theme',dark?'dark':'light')}catch{}},[dark])
 useEffect(()=>{const fn=e=>setView(e.detail);const key=e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();setSearch(v=>!v)}if(e.key==='Escape')document.body.classList.remove('sidebar-open')};window.addEventListener('erp:navigate',fn);window.addEventListener('keydown',key);return()=>{window.removeEventListener('erp:navigate',fn);window.removeEventListener('keydown',key)}},[])
 const results=[...entries.map(([id,name,icon])=>({id,name,icon,type:'Page'})),...db.students.map(s=>({id:s.id,name:s.name,icon:IconSchool,type:'Student',hint:s.family}))].filter(x=>(x.name+' '+(x.hint||'')).toLowerCase().includes(query.toLowerCase())).slice(0,12)
 const runResult=r=>{setSearch(false);setQuery('');r.type==='Student'?window.openProfileModal(r.id):navigate(r.id)}
 const title=entries.find(e=>e[0]===view)?.[1]||'Notifications'
 return <>
  <button className="erp-mobile-overlay" aria-label="Close navigation" onClick={()=>document.body.classList.remove('sidebar-open')}/>
  <aside className="erp-sidebar" aria-label="Main navigation">
   <a href="#dashboard" className="erp-brand" onClick={e=>{e.preventDefault();navigate('dashboard')}}><span className="brandmark"><IconSchool size={23} stroke={1.6}/></span><div><strong>NockERP</strong><small>Education workspace</small></div></a>
   <DropdownMenu><DropdownMenuTrigger asChild><button className="erp-workspace"><IconBuilding size={18}/><span>{user.branch}<small>Academy workspace</small></span><IconSelector size={14}/></button></DropdownMenuTrigger><DropdownMenuContent align="start" className="w-56"><DropdownMenuLabel>Switch branch</DropdownMenuLabel>{window.CONST.BRANCHES.map(b=><DropdownMenuItem key={b} onSelect={()=>{window.CURRENT_USER.branch=b;window.updateUserCard();setUser({...window.CURRENT_USER});emit()}}>{b}{b===user.branch&&<IconCheck className="ml-auto" size={14}/>}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu>
   <nav className="erp-nav">{groups.map(([label,items])=><div className="erp-nav-group" key={label}><p className="erp-nav-label">{label}</p>{items.map(([id,name,Icon])=><button key={id} className="erp-nav-link" aria-current={view===id?'page':undefined} onClick={()=>navigate(id)}><Icon/>{name}{id==='inbox'&&<span className="count">{db.conversations.filter(c=>c.unread>0).length}</span>}</button>)}</div>)}</nav>
   <div className="erp-user"><Avatar name={user.name}/><div><strong>{user.name}</strong><small>{user.role==='director'?'Director':user.role}</small></div><DropdownMenu><DropdownMenuTrigger asChild><button className="erp-icon-button ml-auto" aria-label="Account menu"><IconSelector/></button></DropdownMenuTrigger><DropdownMenuContent side="top" align="end"><DropdownMenuLabel>{user.email}</DropdownMenuLabel><DropdownMenuSeparator/><DropdownMenuItem onSelect={()=>window.openSwitchModal()}><IconSettings size={16}/>Account & preferences</DropdownMenuItem><DropdownMenuItem onSelect={()=>window.logout()}><IconLogout size={16}/>Log out</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>
  </aside>
  <header className="erp-topbar"><button className="erp-icon-button" aria-label="Toggle navigation" onClick={()=>document.body.classList.toggle('sidebar-open')}><IconLayoutSidebar/></button><div className="erp-breadcrumb"><span>Workspace</span><IconChevronRight size={12}/><strong>{title}</strong></div><div className="erp-top-actions"><button className="erp-search-trigger" onClick={()=>setSearch(true)}><IconSearch size={15}/>Search anything…<kbd>⌘ K</kbd></button><button className="erp-icon-button" title={dark?'Switch to light mode':'Switch to dark mode'} aria-label={dark?'Switch to light mode':'Switch to dark mode'} onClick={()=>setDark(v=>!v)}>{dark?<IconSun/>:<IconMoon/>}</button><button className="erp-icon-button" aria-label="Notifications" onClick={()=>navigate('notifications')}><IconBell/></button><Avatar name={user.name}/></div></header>
  <Dialog open={search} onOpenChange={setSearch}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>Search workspace</DialogTitle><DialogDescription>Find a page, student or family.</DialogDescription></DialogHeader><Input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by name…" onKeyDown={e=>{if(e.key==='Enter'&&results[0])runResult(results[0])}}/><div className="max-h-80 overflow-auto">{results.map(r=><button className="flex items-center gap-3 w-full p-3 text-sm rounded-lg hover:bg-accent text-left" key={r.type+r.id} onClick={()=>runResult(r)}><r.icon size={18}/><span>{r.name}{r.hint&&<small className="block text-muted-foreground text-xs">{r.hint}</small>}</span><span className="ml-auto text-xs text-muted-foreground">{r.type}</span></button>)}{!results.length&&<p className="erp-empty">No results for “{query}”.</p>}</div></DialogContent></Dialog>
 </>
}

function Dashboard(){
 useRefresh()
 const [date,setDate]=useState(modelDate),[tab,setTab]=useState('overview'),[follow,setFollow]=useState(null),[note,setNote]=useState(''),[channel,setChannel]=useState('Phone call'),[saved,setSaved]=useState('')
 const [branch,setBranch]=useState('all')
 const students=db.students.filter(s=>branch==='all'||s.branch===branch)
 const active=students.filter(s=>['active','renewal'].includes(s.status))
 const renewals=students.filter(s=>window.Utils.renewalStatus(s.id)==='renewal').sort((a,b)=>window.Utils.classesLeft(a.id)-window.Utils.classesLeft(b.id))
 const leads=db.leads.filter(l=>l.stage!=='archived'&&(branch==='all'||l.branch===branch))
 const sessions=db.sessions.filter(s=>s.date===date&&(branch==='all'||s.branch===branch)).sort((a,b)=>a.slotId-b.slotId)
 const invoices=students.flatMap(s=>(s.invoices||[]).map(i=>({...i,student:s.name})))
 const revenue=invoices.filter(i=>i.status==='paid'&&i.date.startsWith(modelDate.slice(0,7))).reduce((a,i)=>a+i.amount,0)
 const saveFollow=e=>{e.preventDefault();if(!note.trim())return;follow.notes.push({type:'admin',text:`${channel}: ${note.trim()}`,author:window.CURRENT_USER.name,date:new Date().toISOString().slice(0,10)});setSaved('Follow-up saved for '+follow.name);setFollow(null);setNote('');emit()}
 const exportOverview=()=>{const rows=[['Metric','Value'],['Active students',active.length],['Renewals pending',renewals.length],['Paid revenue May 2026',revenue],['Active leads',leads.length]];const blob=new Blob([rows.map(r=>r.join(',')).join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='nockerp-overview.csv';a.click();URL.revokeObjectURL(a.href)}
 return <>
  <div className="erp-heading"><div><h1>Overview</h1><p>Welcome back, Nock. Here's what's happening at your academy.</p></div><div className="erp-heading-actions"><ActionButton variant="outline" className="date-button" onClick={exportOverview}><IconDownload/>Export</ActionButton><DropdownMenu><DropdownMenuTrigger asChild><Button className="erp-button"><IconPlus/>Quick action<IconChevronDown/></Button></DropdownMenuTrigger><DropdownMenuContent align="end">{[['crm','Add a lead'],['students','View students'],['billing','Create an invoice'],['sessions','Manage sessions'],['tasks','Manage tasks']].map(([id,label])=><DropdownMenuItem key={id} onSelect={()=>navigate(id)}>{label}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu></div></div>
  <div className="erp-tabs"><Tabs value={tab} onValueChange={setTab}><TabsList className="h-9 rounded-lg bg-muted p-1"><TabsTrigger className="text-xs rounded-md px-4" value="overview">Overview</TabsTrigger><TabsTrigger className="text-xs rounded-md px-4" value="activity">Recent activity</TabsTrigger></TabsList></Tabs><div className="flex items-center gap-3"><small>Sample data · May 2026</small><DropdownMenu><DropdownMenuTrigger asChild><button className="erp-button flex items-center gap-2 text-xs border rounded-lg px-3"><IconBuilding size={14}/>{branch==='all'?'All branches':branch}<IconChevronDown size={12}/></button></DropdownMenuTrigger><DropdownMenuContent align="end">{['all',...window.CONST.BRANCHES].map(b=><DropdownMenuItem key={b} onSelect={()=>setBranch(b)}>{b==='all'?'All branches':b}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu></div></div>
  {saved&&<div role="status" className="text-sm border rounded-lg bg-muted p-3 mb-4 flex justify-between">{saved}<button onClick={()=>setSaved('')} aria-label="Dismiss">×</button></div>}
  {tab==='overview'?<>
  <div className="erp-metrics">{[[IconSchool,'Active students',active.length,`${students.length} total enrolled`],[IconRefresh,'Renewals pending',renewals.length,`${renewals.filter(s=>window.Utils.classesLeft(s.id)<=1).length} need immediate follow-up`],[IconCreditCard,'Revenue · May',money(revenue),'Paid student invoices this month'],[IconUsers,'Active leads',leads.length,`${leads.filter(l=>l.stage==='new').length} new leads to contact`]].map(([Icon,label,value,detail])=><Card className="erp-metric" key={label}><div className="erp-metric-label">{label}<Icon/></div><div className="erp-metric-value">{value}</div><div className="erp-metric-footer">{detail}</div></Card>)}</div>
  <div className="erp-dashboard-grid"><div><Card className="erp-panel"><div className="erp-panel-heading"><div><h2>Class schedule <Badge className="erp-badge ml-2">{sessions.length} classes</Badge></h2><p>{new Date(date+'T12:00:00').toLocaleDateString('en-US',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</p></div><button className="erp-icon-button" title="Open calendar" aria-label="Open calendar" onClick={()=>navigate('calendar')}><IconArrowUpRight/></button></div><div className="erp-mini-calendar">{db.dayHeaders.map(d=><button key={d.date} className={'erp-day '+(date===d.date?'selected':'')} onClick={()=>setDate(d.date)} aria-pressed={date===d.date}><small>{d.label.split(' ')[0]}</small><strong>{d.label.split(' ')[1]}</strong></button>)}</div>{sessions.map(s=><button className={'erp-session '+s.state} key={s.id} onClick={()=>window.openClassModal(s.id)}><span className="erp-session-time">{window.CONST.SLOT_HOURS[s.slotId]?.s}<small>{window.CONST.SLOT_HOURS[s.slotId]?.e}</small></span><span className="erp-session-divider"/><span><span className="erp-session-title">{s.subject} <span className="text-muted-foreground font-normal">{s.grade}</span></span><span className="erp-session-meta"><span>{s.teacher}</span><span>·</span><span>{s.room}</span><span>·</span><span>{s.studentNames.length} students</span></span></span><Badge className="erp-badge">{s.state==='active'?'In progress':s.state==='ended'?'Completed':'Upcoming'}</Badge><IconChevronRight/></button>)}{!sessions.length&&<p className="erp-empty">No classes scheduled for this day.</p>}<button className="erp-card-footer" onClick={()=>navigate('calendar')}>View full calendar<IconArrowRight/></button></Card>
  <Card className="erp-panel erp-lower"><div className="erp-panel-heading"><div><h2>Recent payments</h2><p>Latest paid invoices across your students</p></div><button className="erp-icon-button" aria-label="Open billing" onClick={()=>navigate('billing')}><IconArrowUpRight/></button></div>{invoices.filter(i=>i.status==='paid').sort((a,b)=>b.date.localeCompare(a.date)).slice(0,3).map(i=><div className="erp-activity" key={i.id}><Avatar name={i.student}/><div><strong className="font-medium">{i.student}</strong><small>{i.id} · {i.date}</small></div><strong className="ml-auto text-xs font-medium">{money(i.amount)}</strong><Badge className="erp-badge">Paid</Badge></div>)}{!invoices.some(i=>i.status==='paid')&&<p className="erp-empty">No paid invoices.</p>}</Card></div>
  <div className="erp-right-column"><Card className="erp-panel"><div className="erp-panel-heading"><div><h2>Renewals to follow up</h2><p>Keep every student's learning on track</p></div><Badge className="erp-badge">{renewals.length}</Badge></div>{renewals.map(s=><div className="erp-renewal" key={s.id}><button aria-label={'Open '+s.name} onClick={()=>window.openProfileModal(s.id)}><Avatar name={s.name}/></button><div><strong>{s.name}</strong><small>{s.courses[0]?.name}</small></div><Badge className={'erp-badge '+(window.Utils.classesLeft(s.id)<=1?'urgent':'')}>{window.Utils.classesLeft(s.id)} left</Badge><button className="erp-icon-button" title={'Follow up '+s.name} aria-label={'Follow up '+s.name} onClick={()=>{setFollow(s);setNote('')}}><IconPhone size={15}/></button></div>)}{!renewals.length&&<p className="erp-empty">All students are up to date.</p>}<button className="erp-card-footer" onClick={()=>navigate('students')}>View all students<IconArrowRight/></button></Card>
  <Card className="erp-panel"><div className="erp-panel-heading"><div><h2>Admissions pipeline</h2><p>{leads.length} active opportunities</p></div><button className="erp-icon-button" aria-label="Open CRM" onClick={()=>navigate('crm')}><IconArrowUpRight/></button></div><div className="erp-pipeline">{[['New leads',['new']],['Contacting',['contacting']],['Test & trial',['test_scheduled','tested','trial_scheduled','trialed']],['Awaiting payment',['payment_pending']],['Enrolled',['enrolled']]].map(([label,stages],i)=>{const count=leads.filter(l=>stages.includes(l.stage)).length;return <div className="erp-pipeline-row" key={label}><span>{label}</span><span className="erp-bar-track"><i style={{width:`${leads.length?count/leads.length*100:0}%`,background:`var(--chart-${Math.min(i+1,5)})`}}/></span><strong>{count}</strong></div>})}</div><button className="erp-card-footer" onClick={()=>navigate('crm')}>Open pipeline<IconArrowRight/></button></Card></div></div>
  </>:<Card className="erp-panel"><div className="erp-panel-heading"><div><h2>Student activity</h2><p>Notes and follow-ups in this workspace</p></div></div>{students.flatMap(s=>s.notes.map((n,i)=>({...n,student:s.name,id:s.id+i}))).reverse().map(n=><div key={n.id} className="erp-activity"><Avatar name={n.student}/><div><strong className="font-medium">{n.student}</strong><small>{n.text}</small></div><time>{n.date}</time></div>)}</Card>}
  <Dialog open={!!follow} onOpenChange={v=>{if(!v)setFollow(null)}}><DialogContent><DialogHeader><DialogTitle>Follow up · {follow?.name}</DialogTitle><DialogDescription>Record your conversation with the parent.</DialogDescription></DialogHeader><form onSubmit={saveFollow} className="grid gap-4"><div className="text-sm rounded-lg bg-muted p-3">Phone: {follow?.phone}<br/>LINE: {follow?.line}</div><label className="text-sm grid gap-2">Channel<select className="border p-2" value={channel} onChange={e=>setChannel(e.target.value)}><option>Phone call</option><option>LINE</option><option>Email</option></select></label><label className="text-sm grid gap-2">Contact note<textarea className="border p-3 min-h-28" required value={note} onChange={e=>setNote(e.target.value)} placeholder="What did you discuss?"/></label><div className="flex justify-end gap-2"><ActionButton type="button" variant="outline" onClick={()=>setFollow(null)}>Cancel</ActionButton><ActionButton type="submit">Save follow-up</ActionButton></div></form></DialogContent></Dialog>
 </>
}

if(!window.__erpBridgeInstalled){installOperationsBridge();window.__erpBridgeInstalled=true}
window.__erpRoots ||= {};
const mount=(id,component)=>{const root=window.__erpRoots[id] ||= createRoot(document.getElementById(id));root.render(component)};
mount('view-students',<Students/>);
mount('shell-root',<Shell/>);
mount('view-dashboard',<Dashboard/>);
const first=location.hash.slice(1);if(entries.some(e=>e[0]===first)||first==='notifications')window.showView(first)
window.addEventListener('hashchange',()=>{const id=location.hash.slice(1);if(entries.some(e=>e[0]===id)||id==='notifications')window.showView(id)})
