import React,{useState,useEffect} from 'react'
import {IconSearch,IconDownload,IconArrowsSort,IconMessage,IconChevronRight,IconSchool,IconRefresh,IconPlayerPause,IconArchive} from '@tabler/icons-react'
import {Button} from '@/components/ui/button'
import {Input} from '@/components/ui/input'
import {Card} from '@/components/ui/card'
import {Badge} from '@/components/ui/badge'
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs'
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table'

export default function Students(){
 const [query,setQuery]=useState(''),[status,setStatus]=useState('all'),[branch,setBranch]=useState('all'),[sort,setSort]=useState({key:'name',asc:true}),[,refresh]=useState(0)
 useEffect(()=>{const update=()=>refresh(v=>v+1);window.addEventListener('erp:data',update);window.addEventListener('erp:navigate',update);return()=>{window.removeEventListener('erp:data',update);window.removeEventListener('erp:navigate',update)}},[])
 const db=window.DB,utils=window.Utils
 const all=db.students
 const list=all.filter(s=>(status==='all'||utils.renewalStatus(s.id)===status)&&(branch==='all'||s.branch===branch)&&[s.name,s.nick,s.family,...s.courses.map(c=>c.name)].join(' ').toLowerCase().includes(query.toLowerCase())).sort((a,b)=>{const av=sort.key==='left'?utils.classesLeft(a.id):sort.key==='status'?utils.renewalStatus(a.id):a.name;const bv=sort.key==='left'?utils.classesLeft(b.id):sort.key==='status'?utils.renewalStatus(b.id):b.name;return (typeof av==='number'?av-bv:av.localeCompare(bv))*(sort.asc?1:-1)})
 const order=key=>setSort(s=>({key,asc:s.key===key?!s.asc:true}))
 const exportRows=()=>{const rows=[['Student','Nickname','Family','Branch','Status','Classes left'],...list.map(s=>[s.name,s.nick,s.family,s.branch,utils.renewalStatus(s.id),utils.classesLeft(s.id)])];const quote=v=>'"'+String(v??'').replaceAll('"','""')+'"';const blob=new Blob(['\uFEFF'+rows.map(r=>r.map(quote).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='nockerp-students.csv';a.click();URL.revokeObjectURL(a.href)}
 return <>
 <div className="erp-heading"><div><h1>Students</h1><p>Manage your students, courses and learning progress.</p></div><Button variant="outline" className="erp-button" onClick={exportRows}><IconDownload/>Export students</Button></div>
 <div className="erp-metrics">{[[IconSchool,'Active','active'],[IconRefresh,'Renewal pending','renewal'],[IconPlayerPause,'Paused','pause'],[IconArchive,'Archived','archived']].map(([Icon,label,key])=><Card key={key} className="erp-metric"><button className="w-full text-left" onClick={()=>setStatus(key)}><div className="erp-metric-label">{label}<Icon/></div><div className="erp-metric-value">{all.filter(s=>utils.renewalStatus(s.id)===key).length}</div><span className="erp-metric-footer">View {label.toLowerCase()} students<IconChevronRight/></span></button></Card>)}</div>
 <Card className="erp-panel"><div className="erp-student-toolbar"><Tabs value={status} onValueChange={setStatus}><TabsList className="h-9 rounded-lg"><TabsTrigger value="all" className="text-xs">All students <span className="ml-2 text-muted-foreground">{all.length}</span></TabsTrigger><TabsTrigger value="active" className="text-xs">Active</TabsTrigger><TabsTrigger value="renewal" className="text-xs">Renewal</TabsTrigger><TabsTrigger value="pause" className="text-xs">Paused</TabsTrigger><TabsTrigger value="archived" className="text-xs">Archived</TabsTrigger></TabsList></Tabs><div className="flex items-center gap-2 erp-student-filters"><div className="relative"><IconSearch size={15} className="absolute top-2.5 left-3 text-muted-foreground"/><Input className="pl-9 h-9 text-xs w-52" placeholder="Search students…" aria-label="Search students" value={query} onChange={e=>setQuery(e.target.value)}/></div><select className="border h-9 px-3 text-xs" aria-label="Filter students by branch" value={branch} onChange={e=>setBranch(e.target.value)}><option value="all">All branches</option>{window.CONST.BRANCHES.map(b=><option key={b}>{b}</option>)}</select></div></div>
 <Table><TableHeader><TableRow><TableHead><button className="flex items-center gap-2" onClick={()=>order('name')}>Student<IconArrowsSort size={13}/></button></TableHead><TableHead>Family</TableHead><TableHead>Branch</TableHead><TableHead>Courses</TableHead><TableHead><button className="flex items-center gap-2" onClick={()=>order('left')}>Remaining<IconArrowsSort size={13}/></button></TableHead><TableHead><button className="flex items-center gap-2" onClick={()=>order('status')}>Status<IconArrowsSort size={13}/></button></TableHead><TableHead><span className="sr-only">Actions</span></TableHead></TableRow></TableHeader><TableBody>{list.map(s=>{const remaining=utils.classesLeft(s.id),state=utils.renewalStatus(s.id);return <TableRow key={s.id}><TableCell><button className="flex gap-3 items-center text-left" onClick={()=>window.openProfileModal(s.id)}><span className="avatar">{s.name.split(' ').map(n=>n[0]).join('')}</span><span className="font-medium whitespace-nowrap">{s.name}<small className="block text-xs font-normal text-muted-foreground mt-1">{s.nick} · {s.age} years</small></span></button></TableCell><TableCell><button className="text-left hover:underline" onClick={()=>window.openProfileModal(s.id)}>{s.family}</button></TableCell><TableCell>{s.branch}</TableCell><TableCell><div className="flex flex-col gap-1">{s.courses.map(c=><span key={c.name} className="text-xs whitespace-nowrap">{c.name}</span>)}</div></TableCell><TableCell><span className={remaining<=1?'text-destructive':'text-foreground'}>{remaining} classes</span><span className="erp-hours-track"><i style={{width:Math.max(0,Math.min(100,s.courses.reduce((v,c)=>v+c.left,0)/Math.max(1,s.courses.reduce((v,c)=>v+c.hours,0))*100))+'%'}}/></span></TableCell><TableCell><Badge className={'erp-badge '+(state==='renewal'&&remaining<=1?'urgent':'')}>{state==='pause'?'Paused':state[0].toUpperCase()+state.slice(1)}</Badge></TableCell><TableCell><div className="flex gap-1"><button className="erp-icon-button" aria-label={'Message '+s.family} onClick={()=>window.openInboxFor(s.family)}><IconMessage size={16}/></button><button className="erp-icon-button" aria-label={'View '+s.name} onClick={()=>window.openProfileModal(s.id)}><IconChevronRight size={16}/></button></div></TableCell></TableRow>})}{!list.length&&<TableRow><TableCell colSpan={7}><div className="erp-empty">No students match these filters.<button className="block mx-auto mt-3 underline" onClick={()=>{setQuery('');setStatus('all');setBranch('all')}}>Clear filters</button></div></TableCell></TableRow>}</TableBody></Table>
 <div className="erp-student-footer">Showing {list.length} of {all.length} students<span>Sample workspace · May 2026</span></div></Card>
 </>
}
